"""
Django settings for katalog project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from django.contrib.messages import constants as message_constants
from collections import OrderedDict

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname((__file__))
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')
STATIC_DIR = os.path.join(BASE_DIR, 'static')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

INSTALLED_APPS = [
    'admin_interface',
    'django.contrib.auth',
    'mainapp.apps.MainappConfig',
    'colorfield',
    'flat_responsive',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'smart_selects',
    'activatable_model',
    'bootstrap3',
    'mainapp.apps.ConstanceConfig',
    'constance.backends.database',
    'kronos',
    'ckeditor',
    'django_admin_listfilter_dropdown',
    'snowpenguin.django.recaptcha2',
    'analytical',
]

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'width': '100%',
        'height': 120,
        'extraPlugins': 'wordcount,notification',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-',
                'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor']
        ]
    },
}

MESSAGE_TAGS = {message_constants.DEBUG: 'debug',
                message_constants.INFO: 'info',
                message_constants.SUCCESS: 'success',
                message_constants.WARNING: 'warning',
                message_constants.ERROR: 'danger', }

# Konfiguracja Django-constance (ustawienia katalogu)

CONSTANCE_CONFIG = OrderedDict([
    ('SITE_TITLE', ('Katalog', 'Tytuł katalogu', str)),
    ('SITE_KEYWORDS', ('katalog stron, najlepszy katalog stron, katalogus, \
            katalog seo', 'Meta keywords katalogu', str)),
    ('SITE_DESCRIPTION', ('To jest najlepszy skrypt katalogu stron jaki \
        kiedykolwiek powstał', 'Meta description katalogu', str)),
    ('TITLE_LENGTH_MAX', (50, 'Maksymalna ilość znaków tytułu strony', int)),
    ('TITLE_LENGTH_MIN', (5, 'Minimalna ilość znaków tytułu strony', int)),
    ('KEYWORDS_LENGTH_MAX', (100, 'Maksymalna ilość znaków słów kluczowych', int)),
    ('KEYWORDS_LENGTH_MIN', (20, 'Minimalna ilość znaków słów kluczowych', int)),
    ('DESCRIPTION_LENGTH_MAX', (250, 'Maksymalna ilość znaków opisu strony', int)),
    ('DESCRIPTION_LENGTH_MIN', (100, 'Minimalna ilość znaków opisu strony', int)),
    ('BOX_PREMIUM', ('tak', 'Czy wyświetlac okienko reklamowe', 'yes_no')),
    ('SHRINKTHEWEB_KEY', ('', 'Access Key serwisu ShrinkTheWeb', str)),
    ('CHECK_SITES', ('tak', 'Czy włączyć sprawdzanie poprawności wczytywania stron', 'yes_no')),
    ('EVIL_WORDS', ('sex, seks, anal, viagra', 'Podejrzane słowa', str)),
    ('EVIL_WORDS_COUNT', (4, 'Minimalna ilość podejrzanych słów kluczowych', int)),
    ('DELETE_SITES', ('nie', 'Czy automatycznie usuwać niedziałające wpisy?', 'yes_no')),
    ('WPISY_DO_MODERACJI', ('tak', 'Czy wysyłać codziennie maila o ilości wpisów do moderacji', 'yes_no')),
    ('ILOSC_WPISOW', (5, 'Wysyłka maila o ilości wpisów do moderacji po przekroczeniu liczby wpisów', int)),
    ('EDYTOR_WYSWIG', ('tak', 'Czy używać edytowa WYSWIG w formularzu dodawania strony?', 'yes_no')),
    ('DESC_LINKS', (0, 'Ile linków można wstawić do opisu strony', int)),
    ('DESC', ('Opis katalogu', 'Opis/wprowadzenie katalogu na stronie głównej', 'wyswig')),
    ('EMAIL_TEMPLATES', ('', 'Wzory maila o odrzuceniu wpisu', str)),
    ('CAPTCHA', ('tak', 'Czy włączyć zabezpieczenie CAPTCHA w formularzu kontaktowym', 'yes_no')),
])

CONSTANCE_CONFIG_FIELDSETS = {
    'Opcje generalne': ('DESC', 'SITE_TITLE', 'SITE_KEYWORDS', 'SITE_DESCRIPTION', 'BOX_PREMIUM',
                        'SHRINKTHEWEB_KEY', 'CAPTCHA'),
    'Opcje dodawania wpisów': ('TITLE_LENGTH_MAX', 'TITLE_LENGTH_MIN',
                               'KEYWORDS_LENGTH_MAX', 'KEYWORDS_LENGTH_MIN',
                               'DESCRIPTION_LENGTH_MAX', 'DESCRIPTION_LENGTH_MIN', 'EDYTOR_WYSWIG',
                               'DESC_LINKS', 'EMAIL_TEMPLATES'),
    'Opcje zadań cyklicznych': ('CHECK_SITES', 'EVIL_WORDS', 'EVIL_WORDS_COUNT',
                                'DELETE_SITES', 'WPISY_DO_MODERACJI', 'ILOSC_WPISOW')
}

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_ADDITIONAL_FIELDS = {
    'yes_no': ['django.forms.fields.ChoiceField', {
        'widget': 'django.forms.Select',
        'choices': (("tak", "Tak"), ("nie", "Nie"),)
    }],
    'wyswig': ['django.forms.fields.CharField', {
        'widget': "ckeditor.widgets.CKEditorWidget",
    }],
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


SESSION_EXPIRE_AT_BROWSER_CLOSE = True

ROOT_URLCONF = 'katalog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mainapp.processor.my_context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'katalog.wsgi.application'


# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTOCOL', 'https')
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}


# Active, inactive users
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.AllowAllUsersModelBackend']

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_L10N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATICFILES_DIRS = [STATIC_DIR, ]
STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

ENV_PATH = os.path.abspath(os.path.dirname(__file__))
STATIC_ROOT = os.path.join(ENV_PATH, '../public/static/')

from .settings_secret import *
